# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "14.x"
    displayName: "Install Node.js"

  - task: 
      cd my-app
      npm install
      npm test
    displayName: "Install dependencies and run tests"

  - task: CopyFiles@2
    inputs:
    sourceFolder: 'my-app/build'
    targetFolder: '$(Build.ArtifactStagingDirectory)/build'
    displayName: 'Copy build artifacts'

- task: PublishBuildArtifacts@1
    inputs:
    artifactName: 'build'
    displayName: 'Publish build artifacts'
